# Generated by Django 4.2.1 on 2023-06-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Libro')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ID del Libro')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor del libro')),
                ('tipo', models.CharField(max_length=15, verbose_name='Autor del libro')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de copias')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria del Libro')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Ingreso')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
            },
        ),
    ]
