# Generated by Django 4.2.1 on 2023-06-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrarLibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad de copias'),
        ),
    ]
