# Generated by Django 4.2.1 on 2023-06-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrarLibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Libro'),
        ),
    ]
