# Generated by Django 4.2.1 on 2023-07-01 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrarLibros', '0003_alter_libro_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Copias Internas'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cantidadext',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Copias Externas'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Cota del Libro'),
        ),
    ]
