# Generated by Django 4.2.1 on 2023-07-01 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrarLibros', '0003_alter_libro_cantidad_alter_libro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidadext',
            field=models.PositiveIntegerField(default='3', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Copias Externas'),
            preserve_default=False,
        ),
    ]
