# Generated by Django 4.2.1 on 2023-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrarLibros', '0006_libro_cantidadint'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='Esto es una descripcion', max_length=50, verbose_name='Descripcion del Libro'),
            preserve_default=False,
        ),
    ]
