# Generated by Django 4.2.1 on 2023-07-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrarLibros', '0007_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('Tesis', 'Tesis'), ('Libros', 'Libro')], max_length=8, verbose_name='Autor del libro'),
        ),
    ]
