# Generated by Django 4.2.1 on 2023-06-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del Estudiante')),
                ('cedula', models.CharField(max_length=20, verbose_name='CI del Estudiante')),
                ('email', models.EmailField(max_length=20, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección del Estudiante')),
                ('tfno', models.CharField(max_length=20, verbose_name='Número Telefónico')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Registro')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
    ]
