# Generated by Django 4.2.1 on 2023-07-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrarEstudiantes', '0005_alter_estudiante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estatus',
            field=models.CharField(default='Habilitado', max_length=30),
        ),
    ]
