# Generated by Django 4.2.1 on 2023-07-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrarEstudiantes', '0006_estudiante_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='devoluciones',
            field=models.IntegerField(default=0, verbose_name='Devoluciones'),
        ),
    ]
