# Generated by Django 4.2.1 on 2023-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('codigo', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('limite', models.DateField(default='')),
                ('cedula', models.CharField(max_length=30, verbose_name='Cédula del estudiante')),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'prestamos',
            },
        ),
    ]
