# Generated by Django 4.2.1 on 2023-06-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='nombre',
            field=models.CharField(default=False, max_length=30, verbose_name='Nombre del estudiante'),
            preserve_default=False,
        ),
    ]
