# Generated by Django 4.2.1 on 2023-06-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cedula',
            field=models.CharField(max_length=30),
        ),
    ]
