# Generated by Django 4.2.1 on 2023-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='limite',
            field=models.DateTimeField(),
        ),
    ]
