# Generated by Django 4.2.1 on 2023-06-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
