# Generated by Django 4.2.1 on 2023-06-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0003_alter_prestamo_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cedula',
            field=models.BigIntegerField(max_length=30),
        ),
    ]
