# Generated by Django 4.2.1 on 2023-06-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='nota',
            new_name='id',
        ),
    ]
