# Generated by Django 4.2.1 on 2023-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0003_rename_nota_prestamo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='limite',
            field=models.DateField(editable=False, verbose_name='Fecha límite de Devolución'),
        ),
    ]
