# Generated by Django 4.2.1 on 2023-06-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0003_alter_estudiante_fecha_alter_libro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
