# Generated by Django 4.2.1 on 2023-06-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0004_alter_prestamo_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default=False, verbose_name='Devuetlo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], default='Externo', max_length=7, verbose_name='Tipo de Prestamo'),
            preserve_default=False,
        ),
    ]
