# Generated by Django 4.2.1 on 2023-06-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0004_rename_nota_prestamo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Nota de Prestamo'),
        ),
    ]
