# Generated by Django 4.2.1 on 2023-06-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0004_alter_estudiante_fecha_alter_libro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'estudiante', 'verbose_name_plural': 'estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'prestamo', 'verbose_name_plural': 'prestamos'},
        ),
    ]
