# Generated by Django 4.2.1 on 2023-06-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0005_prestamo_devuelto_prestamo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default=False, editable=False, verbose_name='Devuetlo'),
        ),
    ]
