# Generated by Django 4.2.1 on 2023-06-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0006_alter_prestamo_devuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cantidad',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
