# Generated by Django 4.2.1 on 2023-06-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0007_prestamo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad del libro'),
        ),
    ]
