# Generated by Django 4.2.1 on 2023-06-30 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0008_alter_prestamo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad del libro'),
        ),
    ]
