# Generated by Django 4.2.1 on 2023-07-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0009_alter_prestamo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='penalizacion',
            field=models.CharField(default='No hay penalización', max_length=50),
        ),
    ]
