# Generated by Django 4.2.1 on 2023-07-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0012_prestamo_cantidad_devuelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default='', editable=False, verbose_name='Devuetlo'),
        ),
    ]
