# Generated by Django 4.2.1 on 2023-07-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenerarPrestamo', '0014_alter_prestamo_devuelto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default=False, editable=False, verbose_name='Devuetlo'),
        ),
    ]
